default:
    tags:
        # required by our runners.
        - build

generate-whl:
    stage: build
    image: python:3.8.12-bullseye
    script:
        - python setup.py bdist_wheel
    artifacts:
        paths:
            - "dist/*.whl"

install-whl:
    stage: test
    dependencies:
        - generate-whl
    image: python:3.8.12-bullseye
    script:
        - pip install dist/*.whl

# run only with valid git tag, for releasing purpose
upload-pypi:
    stage: deploy
    image: python:3.8.12-bullseye
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - echo "TODO"

# push changes of master branch to GitHub'
sync-to-github:
    stage: deploy
    image: python:3.8.12-bullseye
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
    script:
        - echo "TODO"
