default:
    tags:
        # required by our runners.
        - build

generate-whl:
    stage: build
    image: python:3.8.12-bullseye
    script:
        - python setup.py bdist_wheel
    artifacts:
        paths:
            - "dist/*.whl"

install-whl:
    stage: test
    dependencies:
        - generate-whl
    image: python:3.8.12-bullseye
    script:
        - pip install dist/*.whl

# run only with valid git tag, for releasing purpose
upload-pypi:
    stage: deploy
    image: python:3.8.12-bullseye
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - export https:proxy=scumaker.org:8580
        - pip install twine
        - python -m build
        # TWINE_PASSWORD and TWINE_USERNAME set in CI variable
        - twine upload dist/*
        # push tag
        - git push https://$GITHUB_PUSH_KEY@github.com/SalimTerryLi/pyAsyncBot.git $CI_COMMIT_TAG

# push changes of master branch to GitHub'
sync-to-github:
    stage: deploy
    image: python:3.8.12-bullseye
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
    script:
        - git checkout master
        - git pull --ff-only
        # shit GFW
        - export https_proxy=http://scumaker.org:8580
        - git push https://$GITHUB_PUSH_KEY@github.com/SalimTerryLi/pyAsyncBot.git
